version: "3.7"
services:
  app:
    container_name: pdfttiki_app
    env_file: ./.env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: docker/php-prod/Dockerfile
      args:
        - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
    volumes:
      - ".:/usr/src/app"
      - "./docker/php-prod/conf/my-php.ini:/usr/local/etc/php/php.ini:ro"
      - "./docker/php-prod/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro"
      - "./docker/uploads/:/usr/src/app/public/uploads"
    working_dir: /usr/src/app

  nginx:
    container_name: pdfttiki_nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    volumes_from:
      - app
    working_dir: /usr/src/app
