version: "3.7"
services:
  app:
    container_name: pasaia-pdf-app
    env_file: ./.env.local
    image: ikerib/pasaia_pdf:0.1
    volumes:
      - "./php/conf/my-php.ini:/usr/local/etc/php/php.ini:ro"
    working_dir: /usr/src/app

  nginx:
    container_name: pasaia-pdf-nginx
    image: ikerib/pasaia_app_nginx:0.1
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    volumes_from:
      - app
    working_dir: /usr/src/app
